version: '3.8'

services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4442-4444:4442-4444"
    networks:
      - grid
    restart: always

  selenium-node-chrome1:
    image: selenium/node-chrome:latest
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
    shm_size: 4g
    
    networks:
      - grid
    restart: always

  selenium-node-chrome2:
    image: selenium/node-chrome:latest
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
    shm_size: 4g
    networks:
      - grid
    restart: always

  selenium-node-chrome3:
    image: selenium/node-chrome:latest
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
    shm_size: 4g
    networks:
      - grid
    restart: always

  selenium-node-chrome4:
    image: selenium/node-chrome:latest
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
    shm_size: 4g
    networks:
      - grid
    restart: always
    
  selenium-node-chrome5:
    image: selenium/node-chrome:latest
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4
    shm_size: 4g
    networks:
      - grid
    restart: always
networks:
  grid:
    driver: bridge


# version: '3'
# services:
#   cloudflared:
#     image: cloudflare/cloudflared:latest
#     command: tunnel --no-autoupdate run --token "eyJhIjoiZjlkODEzMTI1N2Y2ZDU5NGQ2OGIwOWYyMTk3NjM1NzAiLCJ0IjoiOGZiNGUxYWItZGY4ZC00OTEzLTlhMjUtM2I2MjAyYzIyOTk1IiwicyI6Ik56Qm1OV1EwTVRndFpqVTNOQzAwTjJZekxXRXdZVGd0WWpFd1pHRm1PREF3WlRWbCJ9"
#     restart: always
